### ISSUE TITLE
Generate PRs for Hacktoberfest-2k20 by solving problems from Codechef.

### ISSUE THREAD

**Issue by Anishukla** [Anishukla/Codechef_Hacktoberfest-2021#27]
Hello folks, Want to contribute to Hacktoberfest. 
Confused about what to contribute? 
Let's make your task simpler. 
Go and check out the README of this repo and start contributing!
Generate PRs for Hacktoberfest-2k20 by solving problems from Codechef.

Happy Learning!!!

**Comment by IliasKhan** [comment]
Hi, can I some submit div1 solutions..?

**Comment by Anishukla** [comment]
Ya, you can.
Just create a folder for it
!

**Comment by Anishukla** [comment]
Ya, you can.
Just create a folder for it!

**Comment by Siddhant-K-code** [comment]
can i add OCT20B Solutions in CPP ?
